# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'virtual_gift_demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for virtual_gift_demo
  pod 'ZegoUIKitPrebuiltLiveAudioRoom'
  pod 'ZegoUIKitSignalingPlugin','1.2.0'
  pod 'SVGAPlayer', '~> 2.3'

end

pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
	Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['CODE_SIGN_IDENTITY'] = ''
           end
      end
    end
  end
